######################################################################
# Automatically generated by qmake (3.1) Fri Aug 25 22:31:11 2017
######################################################################
TEMPLATE = app
TARGET = nww_login

include($${PWD}/../nwqt.pri)

HEADERS += \
    nww_login.h
SOURCES += \
    login.cpp \
    nww_login.cxx

