######################################################################
# Automatically generated by qmake (3.1) Fri Aug 25 22:31:11 2017
######################################################################
TEMPLATE = app
TARGET = nwwidget

include($${PWD}/../nwqt.pri)

SOURCES += \
    nwwidget.cpp

