######################################################################
# Automatically generated by qmake (3.1) Fri Aug 25 22:31:11 2017
######################################################################
QT += core gui
TEMPLATE = app
TARGET = nwwidget

include($$PWD/../../nwDeployed/nwDeployed.pri)
include($${PWD}/../nwqt.pri)

SOURCES += \
    nwwidget.cpp

